#!/bin/sh
### BEGIN INIT INFO
# Provides:          bubi
# Required-Start:    $remote_fs $time
# Required-Stop:     umountnfs $time
# X-Stop-After:      sendsigs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: bubid server
# Description:      block-chain based server 
#
#
### END INIT INFO

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=bubid
PIDFILE=/var/run/$NAME.pid
install_dir=/usr/local/bubichain
#This is the command to be run, give the full pathname
DAEMON=${install_dir}/bin/bubid
DAEMON_WATCH=${install_dir}/scripts/bubi
DAEMON_OPTS="--exec $DAEMON_WATCH start --log ${install_dir}/log/daemon.log"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

start(){
		$DAEMON_WATCH start
        echo "Starting "$NAME "..."
		start-stop-daemon --start --oknodo --background  --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
        echo "."
}

stop(){
        echo "Stopping "$NAME "..."
		start-stop-daemon --stop --oknodo --pidfile $PIDFILE --retry 10
        echo "."
		$DAEMON_WATCH stop
}

status(){
	var=$(ps -ef|grep -w ${install_dir}/bin/bubid |grep -v grep | wc -l);	
	if [ $var != 0 ];
	then
	echo "bubid is running";
	else
	echo "bubid is not running";
	fi
	
	var=$(ps -ef|grep -w ${install_dir}/bin/bubi |grep -v grep | wc -l);	
	if [ $var != 0 ];
	then
	echo "bubi is running";
	else
	echo "bubi is not running";
	fi
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
		stop 
		start
	;;
  status)
	status
	;;
  *)
	echo "Usage: "$1" {start|stop|restart|status}"
	exit 1
esac

exit 0
