// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: consenter.proto

package protocol;

public final class Consenter {
  private Consenter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionLiteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.TransactionLite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string topic = 1;</code>
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 1;</code>
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>required int64 sequence = 2;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int64 sequence = 2;</code>
     */
    long getSequence();

    /**
     * <code>required string operation = 3;</code>
     */
    boolean hasOperation();
    /**
     * <code>required string operation = 3;</code>
     */
    java.lang.String getOperation();
    /**
     * <code>required string operation = 3;</code>
     */
    com.google.protobuf.ByteString
        getOperationBytes();
  }
  /**
   * <pre>
   *for transaction
   * </pre>
   *
   * Protobuf type {@code protocol.TransactionLite}
   */
  public  static final class TransactionLite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.TransactionLite)
      TransactionLiteOrBuilder {
    // Use TransactionLite.newBuilder() to construct.
    private TransactionLite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionLite() {
      topic_ = "";
      sequence_ = 0L;
      operation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionLite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              topic_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sequence_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              operation_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Consenter.internal_static_protocol_TransactionLite_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Consenter.internal_static_protocol_TransactionLite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Consenter.TransactionLite.class, protocol.Consenter.TransactionLite.Builder.class);
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object topic_;
    /**
     * <code>required string topic = 1;</code>
     */
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_FIELD_NUMBER = 2;
    private long sequence_;
    /**
     * <code>required int64 sequence = 2;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 sequence = 2;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int OPERATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object operation_;
    /**
     * <code>required string operation = 3;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string operation = 3;</code>
     */
    public java.lang.String getOperation() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string operation = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOperationBytes() {
      java.lang.Object ref = operation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, operation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sequence_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, operation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Consenter.TransactionLite)) {
        return super.equals(obj);
      }
      protocol.Consenter.TransactionLite other = (protocol.Consenter.TransactionLite) obj;

      boolean result = true;
      result = result && (hasTopic() == other.hasTopic());
      if (hasTopic()) {
        result = result && getTopic()
            .equals(other.getTopic());
      }
      result = result && (hasSequence() == other.hasSequence());
      if (hasSequence()) {
        result = result && (getSequence()
            == other.getSequence());
      }
      result = result && (hasOperation() == other.hasOperation());
      if (hasOperation()) {
        result = result && getOperation()
            .equals(other.getOperation());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTopic()) {
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
      }
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequence());
      }
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + getOperation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Consenter.TransactionLite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.TransactionLite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.TransactionLite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Consenter.TransactionLite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *for transaction
     * </pre>
     *
     * Protobuf type {@code protocol.TransactionLite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.TransactionLite)
        protocol.Consenter.TransactionLiteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Consenter.internal_static_protocol_TransactionLite_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Consenter.internal_static_protocol_TransactionLite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Consenter.TransactionLite.class, protocol.Consenter.TransactionLite.Builder.class);
      }

      // Construct using protocol.Consenter.TransactionLite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        topic_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        operation_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Consenter.internal_static_protocol_TransactionLite_descriptor;
      }

      public protocol.Consenter.TransactionLite getDefaultInstanceForType() {
        return protocol.Consenter.TransactionLite.getDefaultInstance();
      }

      public protocol.Consenter.TransactionLite build() {
        protocol.Consenter.TransactionLite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Consenter.TransactionLite buildPartial() {
        protocol.Consenter.TransactionLite result = new protocol.Consenter.TransactionLite(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.topic_ = topic_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.operation_ = operation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Consenter.TransactionLite) {
          return mergeFrom((protocol.Consenter.TransactionLite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Consenter.TransactionLite other) {
        if (other == protocol.Consenter.TransactionLite.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          bitField0_ |= 0x00000001;
          topic_ = other.topic_;
          onChanged();
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasOperation()) {
          bitField0_ |= 0x00000004;
          operation_ = other.operation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTopic()) {
          return false;
        }
        if (!hasSequence()) {
          return false;
        }
        if (!hasOperation()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Consenter.TransactionLite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Consenter.TransactionLite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 1;</code>
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder clearTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        topic_ = value;
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000002;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sequence = 2;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object operation_ = "";
      /**
       * <code>required string operation = 3;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string operation = 3;</code>
       */
      public java.lang.String getOperation() {
        java.lang.Object ref = operation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            operation_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string operation = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOperationBytes() {
        java.lang.Object ref = operation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string operation = 3;</code>
       */
      public Builder setOperation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string operation = 3;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        operation_ = getDefaultInstance().getOperation();
        onChanged();
        return this;
      }
      /**
       * <code>required string operation = 3;</code>
       */
      public Builder setOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        operation_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.TransactionLite)
    }

    // @@protoc_insertion_point(class_scope:protocol.TransactionLite)
    private static final protocol.Consenter.TransactionLite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Consenter.TransactionLite();
    }

    public static protocol.Consenter.TransactionLite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransactionLite>
        PARSER = new com.google.protobuf.AbstractParser<TransactionLite>() {
      public TransactionLite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransactionLite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionLite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionLite> getParserForType() {
      return PARSER;
    }

    public protocol.Consenter.TransactionLite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TransactionLiteSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.TransactionLiteSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes preledger_hash = 1;</code>
     */
    boolean hasPreledgerHash();
    /**
     * <code>required bytes preledger_hash = 1;</code>
     */
    com.google.protobuf.ByteString getPreledgerHash();

    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    java.util.List<protocol.Consenter.TransactionLite> 
        getTxsList();
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    protocol.Consenter.TransactionLite getTxs(int index);
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    int getTxsCount();
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    java.util.List<? extends protocol.Consenter.TransactionLiteOrBuilder> 
        getTxsOrBuilderList();
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    protocol.Consenter.TransactionLiteOrBuilder getTxsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *for transaction set
   * </pre>
   *
   * Protobuf type {@code protocol.TransactionLiteSet}
   */
  public  static final class TransactionLiteSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.TransactionLiteSet)
      TransactionLiteSetOrBuilder {
    // Use TransactionLiteSet.newBuilder() to construct.
    private TransactionLiteSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionLiteSet() {
      preledgerHash_ = com.google.protobuf.ByteString.EMPTY;
      txs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionLiteSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              preledgerHash_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                txs_ = new java.util.ArrayList<protocol.Consenter.TransactionLite>();
                mutable_bitField0_ |= 0x00000002;
              }
              txs_.add(
                  input.readMessage(protocol.Consenter.TransactionLite.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          txs_ = java.util.Collections.unmodifiableList(txs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Consenter.internal_static_protocol_TransactionLiteSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Consenter.internal_static_protocol_TransactionLiteSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Consenter.TransactionLiteSet.class, protocol.Consenter.TransactionLiteSet.Builder.class);
    }

    private int bitField0_;
    public static final int PRELEDGER_HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString preledgerHash_;
    /**
     * <code>required bytes preledger_hash = 1;</code>
     */
    public boolean hasPreledgerHash() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes preledger_hash = 1;</code>
     */
    public com.google.protobuf.ByteString getPreledgerHash() {
      return preledgerHash_;
    }

    public static final int TXS_FIELD_NUMBER = 2;
    private java.util.List<protocol.Consenter.TransactionLite> txs_;
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    public java.util.List<protocol.Consenter.TransactionLite> getTxsList() {
      return txs_;
    }
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    public java.util.List<? extends protocol.Consenter.TransactionLiteOrBuilder> 
        getTxsOrBuilderList() {
      return txs_;
    }
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    public int getTxsCount() {
      return txs_.size();
    }
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    public protocol.Consenter.TransactionLite getTxs(int index) {
      return txs_.get(index);
    }
    /**
     * <code>repeated .protocol.TransactionLite txs = 2;</code>
     */
    public protocol.Consenter.TransactionLiteOrBuilder getTxsOrBuilder(
        int index) {
      return txs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPreledgerHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTxsCount(); i++) {
        if (!getTxs(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, preledgerHash_);
      }
      for (int i = 0; i < txs_.size(); i++) {
        output.writeMessage(2, txs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, preledgerHash_);
      }
      for (int i = 0; i < txs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, txs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Consenter.TransactionLiteSet)) {
        return super.equals(obj);
      }
      protocol.Consenter.TransactionLiteSet other = (protocol.Consenter.TransactionLiteSet) obj;

      boolean result = true;
      result = result && (hasPreledgerHash() == other.hasPreledgerHash());
      if (hasPreledgerHash()) {
        result = result && getPreledgerHash()
            .equals(other.getPreledgerHash());
      }
      result = result && getTxsList()
          .equals(other.getTxsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasPreledgerHash()) {
        hash = (37 * hash) + PRELEDGER_HASH_FIELD_NUMBER;
        hash = (53 * hash) + getPreledgerHash().hashCode();
      }
      if (getTxsCount() > 0) {
        hash = (37 * hash) + TXS_FIELD_NUMBER;
        hash = (53 * hash) + getTxsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Consenter.TransactionLiteSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLiteSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLiteSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.TransactionLiteSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Consenter.TransactionLiteSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *for transaction set
     * </pre>
     *
     * Protobuf type {@code protocol.TransactionLiteSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.TransactionLiteSet)
        protocol.Consenter.TransactionLiteSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Consenter.internal_static_protocol_TransactionLiteSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Consenter.internal_static_protocol_TransactionLiteSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Consenter.TransactionLiteSet.class, protocol.Consenter.TransactionLiteSet.Builder.class);
      }

      // Construct using protocol.Consenter.TransactionLiteSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTxsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        preledgerHash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          txsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Consenter.internal_static_protocol_TransactionLiteSet_descriptor;
      }

      public protocol.Consenter.TransactionLiteSet getDefaultInstanceForType() {
        return protocol.Consenter.TransactionLiteSet.getDefaultInstance();
      }

      public protocol.Consenter.TransactionLiteSet build() {
        protocol.Consenter.TransactionLiteSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Consenter.TransactionLiteSet buildPartial() {
        protocol.Consenter.TransactionLiteSet result = new protocol.Consenter.TransactionLiteSet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.preledgerHash_ = preledgerHash_;
        if (txsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            txs_ = java.util.Collections.unmodifiableList(txs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.txs_ = txs_;
        } else {
          result.txs_ = txsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Consenter.TransactionLiteSet) {
          return mergeFrom((protocol.Consenter.TransactionLiteSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Consenter.TransactionLiteSet other) {
        if (other == protocol.Consenter.TransactionLiteSet.getDefaultInstance()) return this;
        if (other.hasPreledgerHash()) {
          setPreledgerHash(other.getPreledgerHash());
        }
        if (txsBuilder_ == null) {
          if (!other.txs_.isEmpty()) {
            if (txs_.isEmpty()) {
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTxsIsMutable();
              txs_.addAll(other.txs_);
            }
            onChanged();
          }
        } else {
          if (!other.txs_.isEmpty()) {
            if (txsBuilder_.isEmpty()) {
              txsBuilder_.dispose();
              txsBuilder_ = null;
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              txsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTxsFieldBuilder() : null;
            } else {
              txsBuilder_.addAllMessages(other.txs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPreledgerHash()) {
          return false;
        }
        for (int i = 0; i < getTxsCount(); i++) {
          if (!getTxs(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Consenter.TransactionLiteSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Consenter.TransactionLiteSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString preledgerHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes preledger_hash = 1;</code>
       */
      public boolean hasPreledgerHash() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes preledger_hash = 1;</code>
       */
      public com.google.protobuf.ByteString getPreledgerHash() {
        return preledgerHash_;
      }
      /**
       * <code>required bytes preledger_hash = 1;</code>
       */
      public Builder setPreledgerHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        preledgerHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes preledger_hash = 1;</code>
       */
      public Builder clearPreledgerHash() {
        bitField0_ = (bitField0_ & ~0x00000001);
        preledgerHash_ = getDefaultInstance().getPreledgerHash();
        onChanged();
        return this;
      }

      private java.util.List<protocol.Consenter.TransactionLite> txs_ =
        java.util.Collections.emptyList();
      private void ensureTxsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          txs_ = new java.util.ArrayList<protocol.Consenter.TransactionLite>(txs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Consenter.TransactionLite, protocol.Consenter.TransactionLite.Builder, protocol.Consenter.TransactionLiteOrBuilder> txsBuilder_;

      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public java.util.List<protocol.Consenter.TransactionLite> getTxsList() {
        if (txsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(txs_);
        } else {
          return txsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public int getTxsCount() {
        if (txsBuilder_ == null) {
          return txs_.size();
        } else {
          return txsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public protocol.Consenter.TransactionLite getTxs(int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);
        } else {
          return txsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder setTxs(
          int index, protocol.Consenter.TransactionLite value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.set(index, value);
          onChanged();
        } else {
          txsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder setTxs(
          int index, protocol.Consenter.TransactionLite.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.set(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder addTxs(protocol.Consenter.TransactionLite value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(value);
          onChanged();
        } else {
          txsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder addTxs(
          int index, protocol.Consenter.TransactionLite value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(index, value);
          onChanged();
        } else {
          txsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder addTxs(
          protocol.Consenter.TransactionLite.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder addTxs(
          int index, protocol.Consenter.TransactionLite.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder addAllTxs(
          java.lang.Iterable<? extends protocol.Consenter.TransactionLite> values) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, txs_);
          onChanged();
        } else {
          txsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder clearTxs() {
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          txsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public Builder removeTxs(int index) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.remove(index);
          onChanged();
        } else {
          txsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public protocol.Consenter.TransactionLite.Builder getTxsBuilder(
          int index) {
        return getTxsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public protocol.Consenter.TransactionLiteOrBuilder getTxsOrBuilder(
          int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);  } else {
          return txsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public java.util.List<? extends protocol.Consenter.TransactionLiteOrBuilder> 
           getTxsOrBuilderList() {
        if (txsBuilder_ != null) {
          return txsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(txs_);
        }
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public protocol.Consenter.TransactionLite.Builder addTxsBuilder() {
        return getTxsFieldBuilder().addBuilder(
            protocol.Consenter.TransactionLite.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public protocol.Consenter.TransactionLite.Builder addTxsBuilder(
          int index) {
        return getTxsFieldBuilder().addBuilder(
            index, protocol.Consenter.TransactionLite.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.TransactionLite txs = 2;</code>
       */
      public java.util.List<protocol.Consenter.TransactionLite.Builder> 
           getTxsBuilderList() {
        return getTxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Consenter.TransactionLite, protocol.Consenter.TransactionLite.Builder, protocol.Consenter.TransactionLiteOrBuilder> 
          getTxsFieldBuilder() {
        if (txsBuilder_ == null) {
          txsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Consenter.TransactionLite, protocol.Consenter.TransactionLite.Builder, protocol.Consenter.TransactionLiteOrBuilder>(
                  txs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          txs_ = null;
        }
        return txsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.TransactionLiteSet)
    }

    // @@protoc_insertion_point(class_scope:protocol.TransactionLiteSet)
    private static final protocol.Consenter.TransactionLiteSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Consenter.TransactionLiteSet();
    }

    public static protocol.Consenter.TransactionLiteSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TransactionLiteSet>
        PARSER = new com.google.protobuf.AbstractParser<TransactionLiteSet>() {
      public TransactionLiteSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransactionLiteSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionLiteSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionLiteSet> getParserForType() {
      return PARSER;
    }

    public protocol.Consenter.TransactionLiteSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LedgerHeaderLiteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.LedgerHeaderLite)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 sequence = 1;</code>
     */
    boolean hasSequence();
    /**
     * <code>required int64 sequence = 1;</code>
     */
    long getSequence();

    /**
     * <code>required bytes hash = 2;</code>
     */
    boolean hasHash();
    /**
     * <code>required bytes hash = 2;</code>
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>required bytes phash = 3;</code>
     */
    boolean hasPhash();
    /**
     * <code>required bytes phash = 3;</code>
     */
    com.google.protobuf.ByteString getPhash();

    /**
     * <code>required bytes txs_hash = 4;</code>
     */
    boolean hasTxsHash();
    /**
     * <code>required bytes txs_hash = 4;</code>
     */
    com.google.protobuf.ByteString getTxsHash();

    /**
     * <code>required int64 apply_time = 5;</code>
     */
    boolean hasApplyTime();
    /**
     * <code>required int64 apply_time = 5;</code>
     */
    long getApplyTime();

    /**
     * <code>required int64 tx_count = 6;</code>
     */
    boolean hasTxCount();
    /**
     * <code>required int64 tx_count = 6;</code>
     */
    long getTxCount();
  }
  /**
   * <pre>
   *for ledger
   * </pre>
   *
   * Protobuf type {@code protocol.LedgerHeaderLite}
   */
  public  static final class LedgerHeaderLite extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.LedgerHeaderLite)
      LedgerHeaderLiteOrBuilder {
    // Use LedgerHeaderLite.newBuilder() to construct.
    private LedgerHeaderLite(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LedgerHeaderLite() {
      sequence_ = 0L;
      hash_ = com.google.protobuf.ByteString.EMPTY;
      phash_ = com.google.protobuf.ByteString.EMPTY;
      txsHash_ = com.google.protobuf.ByteString.EMPTY;
      applyTime_ = 0L;
      txCount_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LedgerHeaderLite(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sequence_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              hash_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              phash_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              txsHash_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              applyTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              txCount_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Consenter.internal_static_protocol_LedgerHeaderLite_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Consenter.internal_static_protocol_LedgerHeaderLite_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Consenter.LedgerHeaderLite.class, protocol.Consenter.LedgerHeaderLite.Builder.class);
    }

    private int bitField0_;
    public static final int SEQUENCE_FIELD_NUMBER = 1;
    private long sequence_;
    /**
     * <code>required int64 sequence = 1;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 sequence = 1;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString hash_;
    /**
     * <code>required bytes hash = 2;</code>
     */
    public boolean hasHash() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes hash = 2;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int PHASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString phash_;
    /**
     * <code>required bytes phash = 3;</code>
     */
    public boolean hasPhash() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes phash = 3;</code>
     */
    public com.google.protobuf.ByteString getPhash() {
      return phash_;
    }

    public static final int TXS_HASH_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString txsHash_;
    /**
     * <code>required bytes txs_hash = 4;</code>
     */
    public boolean hasTxsHash() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes txs_hash = 4;</code>
     */
    public com.google.protobuf.ByteString getTxsHash() {
      return txsHash_;
    }

    public static final int APPLY_TIME_FIELD_NUMBER = 5;
    private long applyTime_;
    /**
     * <code>required int64 apply_time = 5;</code>
     */
    public boolean hasApplyTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 apply_time = 5;</code>
     */
    public long getApplyTime() {
      return applyTime_;
    }

    public static final int TX_COUNT_FIELD_NUMBER = 6;
    private long txCount_;
    /**
     * <code>required int64 tx_count = 6;</code>
     */
    public boolean hasTxCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 tx_count = 6;</code>
     */
    public long getTxCount() {
      return txCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSequence()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPhash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxsHash()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasApplyTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sequence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, phash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, txsHash_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, applyTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, txCount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sequence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, hash_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, phash_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, txsHash_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, applyTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, txCount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.Consenter.LedgerHeaderLite)) {
        return super.equals(obj);
      }
      protocol.Consenter.LedgerHeaderLite other = (protocol.Consenter.LedgerHeaderLite) obj;

      boolean result = true;
      result = result && (hasSequence() == other.hasSequence());
      if (hasSequence()) {
        result = result && (getSequence()
            == other.getSequence());
      }
      result = result && (hasHash() == other.hasHash());
      if (hasHash()) {
        result = result && getHash()
            .equals(other.getHash());
      }
      result = result && (hasPhash() == other.hasPhash());
      if (hasPhash()) {
        result = result && getPhash()
            .equals(other.getPhash());
      }
      result = result && (hasTxsHash() == other.hasTxsHash());
      if (hasTxsHash()) {
        result = result && getTxsHash()
            .equals(other.getTxsHash());
      }
      result = result && (hasApplyTime() == other.hasApplyTime());
      if (hasApplyTime()) {
        result = result && (getApplyTime()
            == other.getApplyTime());
      }
      result = result && (hasTxCount() == other.hasTxCount());
      if (hasTxCount()) {
        result = result && (getTxCount()
            == other.getTxCount());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequence());
      }
      if (hasHash()) {
        hash = (37 * hash) + HASH_FIELD_NUMBER;
        hash = (53 * hash) + getHash().hashCode();
      }
      if (hasPhash()) {
        hash = (37 * hash) + PHASH_FIELD_NUMBER;
        hash = (53 * hash) + getPhash().hashCode();
      }
      if (hasTxsHash()) {
        hash = (37 * hash) + TXS_HASH_FIELD_NUMBER;
        hash = (53 * hash) + getTxsHash().hashCode();
      }
      if (hasApplyTime()) {
        hash = (37 * hash) + APPLY_TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getApplyTime());
      }
      if (hasTxCount()) {
        hash = (37 * hash) + TX_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTxCount());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.LedgerHeaderLite parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.Consenter.LedgerHeaderLite parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.Consenter.LedgerHeaderLite parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.Consenter.LedgerHeaderLite prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *for ledger
     * </pre>
     *
     * Protobuf type {@code protocol.LedgerHeaderLite}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.LedgerHeaderLite)
        protocol.Consenter.LedgerHeaderLiteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Consenter.internal_static_protocol_LedgerHeaderLite_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Consenter.internal_static_protocol_LedgerHeaderLite_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Consenter.LedgerHeaderLite.class, protocol.Consenter.LedgerHeaderLite.Builder.class);
      }

      // Construct using protocol.Consenter.LedgerHeaderLite.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        hash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        phash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        txsHash_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        applyTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        txCount_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Consenter.internal_static_protocol_LedgerHeaderLite_descriptor;
      }

      public protocol.Consenter.LedgerHeaderLite getDefaultInstanceForType() {
        return protocol.Consenter.LedgerHeaderLite.getDefaultInstance();
      }

      public protocol.Consenter.LedgerHeaderLite build() {
        protocol.Consenter.LedgerHeaderLite result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Consenter.LedgerHeaderLite buildPartial() {
        protocol.Consenter.LedgerHeaderLite result = new protocol.Consenter.LedgerHeaderLite(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hash_ = hash_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phash_ = phash_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.txsHash_ = txsHash_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.applyTime_ = applyTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.txCount_ = txCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Consenter.LedgerHeaderLite) {
          return mergeFrom((protocol.Consenter.LedgerHeaderLite)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Consenter.LedgerHeaderLite other) {
        if (other == protocol.Consenter.LedgerHeaderLite.getDefaultInstance()) return this;
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasHash()) {
          setHash(other.getHash());
        }
        if (other.hasPhash()) {
          setPhash(other.getPhash());
        }
        if (other.hasTxsHash()) {
          setTxsHash(other.getTxsHash());
        }
        if (other.hasApplyTime()) {
          setApplyTime(other.getApplyTime());
        }
        if (other.hasTxCount()) {
          setTxCount(other.getTxCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSequence()) {
          return false;
        }
        if (!hasHash()) {
          return false;
        }
        if (!hasPhash()) {
          return false;
        }
        if (!hasTxsHash()) {
          return false;
        }
        if (!hasApplyTime()) {
          return false;
        }
        if (!hasTxCount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Consenter.LedgerHeaderLite parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Consenter.LedgerHeaderLite) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long sequence_ ;
      /**
       * <code>required int64 sequence = 1;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 sequence = 1;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>required int64 sequence = 1;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000001;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sequence = 1;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes hash = 2;</code>
       */
      public boolean hasHash() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes hash = 2;</code>
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString phash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes phash = 3;</code>
       */
      public boolean hasPhash() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes phash = 3;</code>
       */
      public com.google.protobuf.ByteString getPhash() {
        return phash_;
      }
      /**
       * <code>required bytes phash = 3;</code>
       */
      public Builder setPhash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        phash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes phash = 3;</code>
       */
      public Builder clearPhash() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phash_ = getDefaultInstance().getPhash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString txsHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes txs_hash = 4;</code>
       */
      public boolean hasTxsHash() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes txs_hash = 4;</code>
       */
      public com.google.protobuf.ByteString getTxsHash() {
        return txsHash_;
      }
      /**
       * <code>required bytes txs_hash = 4;</code>
       */
      public Builder setTxsHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        txsHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes txs_hash = 4;</code>
       */
      public Builder clearTxsHash() {
        bitField0_ = (bitField0_ & ~0x00000008);
        txsHash_ = getDefaultInstance().getTxsHash();
        onChanged();
        return this;
      }

      private long applyTime_ ;
      /**
       * <code>required int64 apply_time = 5;</code>
       */
      public boolean hasApplyTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 apply_time = 5;</code>
       */
      public long getApplyTime() {
        return applyTime_;
      }
      /**
       * <code>required int64 apply_time = 5;</code>
       */
      public Builder setApplyTime(long value) {
        bitField0_ |= 0x00000010;
        applyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 apply_time = 5;</code>
       */
      public Builder clearApplyTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        applyTime_ = 0L;
        onChanged();
        return this;
      }

      private long txCount_ ;
      /**
       * <code>required int64 tx_count = 6;</code>
       */
      public boolean hasTxCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 tx_count = 6;</code>
       */
      public long getTxCount() {
        return txCount_;
      }
      /**
       * <code>required int64 tx_count = 6;</code>
       */
      public Builder setTxCount(long value) {
        bitField0_ |= 0x00000020;
        txCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 tx_count = 6;</code>
       */
      public Builder clearTxCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        txCount_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.LedgerHeaderLite)
    }

    // @@protoc_insertion_point(class_scope:protocol.LedgerHeaderLite)
    private static final protocol.Consenter.LedgerHeaderLite DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.Consenter.LedgerHeaderLite();
    }

    public static protocol.Consenter.LedgerHeaderLite getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LedgerHeaderLite>
        PARSER = new com.google.protobuf.AbstractParser<LedgerHeaderLite>() {
      public LedgerHeaderLite parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LedgerHeaderLite(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LedgerHeaderLite> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LedgerHeaderLite> getParserForType() {
      return PARSER;
    }

    public protocol.Consenter.LedgerHeaderLite getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_TransactionLite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_TransactionLite_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_TransactionLiteSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_TransactionLiteSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_LedgerHeaderLite_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_LedgerHeaderLite_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017consenter.proto\022\010protocol\"E\n\017Transacti" +
      "onLite\022\r\n\005topic\030\001 \002(\t\022\020\n\010sequence\030\002 \002(\003\022" +
      "\021\n\toperation\030\003 \002(\t\"T\n\022TransactionLiteSet" +
      "\022\026\n\016preledger_hash\030\001 \002(\014\022&\n\003txs\030\002 \003(\0132\031." +
      "protocol.TransactionLite\"y\n\020LedgerHeader" +
      "Lite\022\020\n\010sequence\030\001 \002(\003\022\014\n\004hash\030\002 \002(\014\022\r\n\005" +
      "phash\030\003 \002(\014\022\020\n\010txs_hash\030\004 \002(\014\022\022\n\napply_t" +
      "ime\030\005 \002(\003\022\020\n\010tx_count\030\006 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_TransactionLite_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_TransactionLite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_TransactionLite_descriptor,
        new java.lang.String[] { "Topic", "Sequence", "Operation", });
    internal_static_protocol_TransactionLiteSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_TransactionLiteSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_TransactionLiteSet_descriptor,
        new java.lang.String[] { "PreledgerHash", "Txs", });
    internal_static_protocol_LedgerHeaderLite_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_LedgerHeaderLite_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_LedgerHeaderLite_descriptor,
        new java.lang.String[] { "Sequence", "Hash", "Phash", "TxsHash", "ApplyTime", "TxCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
